### ISSUE TITLE
Try to use `now_local`

### ISSUE THREAD

**Issue by rudolphfroger-ds** [ObsceneGiraffe/flexi_syslog#1]
Use `time::OffsetDateTime::now_local` with a fallback to `time::OffsetDateTime::now_utc`.

Maybe it's inefficient to do the fallback on every syslog message, so maybe determine if `time::OffsetDateTime::now_local` works on the current system, once at startup.

**Comment by bheylin** [comment]
Resolved in https://github.com/bheylin/flexi_syslog/commit/5a9417021e01a4cb9fa21ad9f978af99b78fc5e9
